Embedded Motor PID Controller: firmware/include/motor.h File Reference
motor.h File Reference
Simple DC motor simulation for testing PID control.
Functions
void motor_init (void)
Initialize motor simulation.
void motor_set_output (float duty_cycle)
Set motor control output.
float motor_get_speed (void)
Get current motor speed.
void motor_update (void)
Update motor simulation (call periodically)
Detailed Description
Simple DC motor simulation for testing PID control.
Author
Onesmo Ogore
Version
1.0.0
Date
November 2025 @license MIT
This is a simulation model for testing PID algorithms. For real hardware, replace motor.c with platform-specific PWM/GPIO/encoder code.
Definition in file motor.h.
Function Documentation
motor_get_speed()
float motor_get_speed (void)
Get current motor speed.
Returns
Simulated motor speed (arbitrary units)
Get current motor speed.
See detailed documentation in motor.h
Implementation notes (simulation):
Returns the simulated motor speed directly (perfect measurement)
No noise, quantization, or measurement delay
Unrealistically perfect feedback
For real hardware implementation:
Read encoder counter value from timer peripheral
Calculate velocity from change in position: velocity = (position[n] - position[n-1]) / Δt
Apply scaling factor to convert counts/sec to desired units (RPM, rad/s)
Optionally apply filtering to reduce encoder noise:
Moving average filter (simple, adds delay)
Low-pass filter (better frequency response)
Or use PID derivative filtering (recommended)
Handle counter overflow/wraparound (16-bit or 32-bit counters)
Example calculation (quadrature encoder):
Encoder resolution: 1000 counts/revolution (CPR)
Time between measurements: 10ms
Measured Δcounts: 50 counts in 10ms
Velocity = (50 counts / 10ms) × (60000 ms/min) / (1000 counts/rev) = 300 RPM
Returns
Current motor speed in arbitrary units (simulation) For hardware: typically RPM, rad/s, or counts/second
Definition at line 106 of file motor.c.
References current_speed.
Referenced by main().
motor_init()
void motor_init (void)
Initialize motor simulation.
Resets motor state to zero speed and zero output.
Initialize motor simulation.
See detailed documentation in motor.h
Implementation notes (simulation):
Resets motor speed to zero (stopped)
Resets control output to zero (no commanded motion)
No actual hardware initialization (this is simulation)
For real hardware implementation:
Initialize PWM peripheral (timer configuration, frequency, resolution)
Configure direction control GPIOs as outputs
Initialize encoder/tachometer interface (timer in encoder mode or GPIO interrupts)
Ensure motor starts in safe stopped state
Optionally enable motor driver (enable pin)
Definition at line 60 of file motor.c.
References current_output, and current_speed.
Referenced by main().
motor_set_output()
void motor_set_output (float duty_cycle)
Set motor control output.
Parameters
duty_cycle Control output (-1.0 to 1.0) Negative = reverse, Positive = forward, 0 = stop
Definition at line 66 of file motor.c.
References current_output.
Referenced by main().
motor_update()
void motor_update (void)
Update motor simulation (call periodically)
Advances the motor model by one time step. Should be called at regular intervals matching the configured sample time.
Definition at line 140 of file motor.c.
References current_output, current_speed, model_alpha, and model_gain.
Referenced by main().