Embedded Motor PID Controller: firmware/src/motor.c File Reference
motor.c File Reference
Simple first-order DC motor simulation model.
#include "motor.h"
Functions
void motor_init (void)
Initialize motor hardware and simulation model.
void motor_set_output (float duty_cycle)
Set motor control output.
float motor_get_speed (void)
Get current motor speed measurement.
void motor_update (void)
Update motor simulation (call periodically)
Variables
static float current_speed = 0.0f
static float current_output = 0.0f
Current motor control output (last commanded duty cycle)
static const float model_gain = 5.0f
static const float model_alpha = 0.05f
Detailed Description
Simple first-order DC motor simulation model.
Author
Onesmo Ogore
Version
1.0.0
Date
November 2025 @license MIT
Implements a linearized first-order motor model for PID testing: speed[n+1] = speed[n] + alpha * (gain * input - speed[n])
For real hardware, replace with platform-specific PWM/encoder code.
Definition in file motor.c.
Function Documentation
motor_get_speed()
float motor_get_speed (void)
Get current motor speed measurement.
Get current motor speed.
See detailed documentation in motor.h
Implementation notes (simulation):
Returns the simulated motor speed directly (perfect measurement)
No noise, quantization, or measurement delay
Unrealistically perfect feedback
For real hardware implementation:
Read encoder counter value from timer peripheral
Calculate velocity from change in position: velocity = (position[n] - position[n-1]) / Δt
Apply scaling factor to convert counts/sec to desired units (RPM, rad/s)
Optionally apply filtering to reduce encoder noise:
Moving average filter (simple, adds delay)
Low-pass filter (better frequency response)
Or use PID derivative filtering (recommended)
Handle counter overflow/wraparound (16-bit or 32-bit counters)
Example calculation (quadrature encoder):
Encoder resolution: 1000 counts/revolution (CPR)
Time between measurements: 10ms
Measured Δcounts: 50 counts in 10ms
Velocity = (50 counts / 10ms) × (60000 ms/min) / (1000 counts/rev) = 300 RPM
Returns
Current motor speed in arbitrary units (simulation) For hardware: typically RPM, rad/s, or counts/second
Definition at line 106 of file motor.c.
References current_speed.
Referenced by main().
motor_init()
void motor_init (void)
Initialize motor hardware and simulation model.
Initialize motor simulation.
See detailed documentation in motor.h
Implementation notes (simulation):
Resets motor speed to zero (stopped)
Resets control output to zero (no commanded motion)
No actual hardware initialization (this is simulation)
For real hardware implementation:
Initialize PWM peripheral (timer configuration, frequency, resolution)
Configure direction control GPIOs as outputs
Initialize encoder/tachometer interface (timer in encoder mode or GPIO interrupts)
Ensure motor starts in safe stopped state
Optionally enable motor driver (enable pin)
Definition at line 60 of file motor.c.
References current_output, and current_speed.
Referenced by main().
motor_set_output()
void motor_set_output (float duty_cycle)
Set motor control output.
Parameters
duty_cycle Control output (-1.0 to 1.0) Negative = reverse, Positive = forward, 0 = stop
Definition at line 66 of file motor.c.
References current_output.
Referenced by main().
motor_update()
void motor_update (void)
Update motor simulation (call periodically)
Advances the motor model by one time step. Should be called at regular intervals matching the configured sample time.
Definition at line 140 of file motor.c.
References current_output, current_speed, model_alpha, and model_gain.
Referenced by main().
Variable Documentation
current_output
float current_output = 0.0f static
Current motor control output (last commanded duty cycle)
Units: Normalized duty cycle Range: -1.0 (full reverse) to +1.0 (full forward)
This stores the most recent value set by motor_set_output() and is used to update the motor model dynamics.
Definition at line 29 of file motor.c.
Referenced by motor_init(), motor_set_output(), and motor_update().
current_speed
float current_speed = 0.0f static
Definition at line 18 of file motor.c.
Referenced by motor_get_speed(), motor_init(), and motor_update().
model_alpha
const float model_alpha = 0.05f static
Definition at line 37 of file motor.c.
Referenced by motor_update().
model_gain
const float model_gain = 5.0f static
Definition at line 36 of file motor.c.
Referenced by motor_update().