Embedded Motor PID Controller: firmware/src/pid.c File Reference
pid.c File Reference
Implementation of production-ready PID controller.
#include "pid.h"
#include <assert.h>
#include <stddef.h>
Functions
static float clamp (float value, float min, float max)
void pid_init (pid_t *pid, float kp, float ki, float kd, float dt, float out_min, float out_max)
Initialize PID controller with standard configuration.
void pid_init_advanced (pid_t *pid, float kp, float ki, float kd, float dt, float out_min, float out_max, float integrator_min, float integrator_max, float derivative_lpf)
Initialize PID controller with advanced options.
float pid_compute (pid_t *pid, float setpoint, float measurement)
Calculate PID control output.
void pid_reset (pid_t *pid)
Reset PID controller internal state.
Detailed Description
Implementation of production-ready PID controller.
Author
Onesmo Ogore
Version
1.0.0
Date
November 2025 @license MIT
Features: Anti-windup via integrator clamping, derivative-on-measurement to avoid derivative kick, optional low-pass filtering for noise reduction.
Definition in file pid.c.
Function Documentation
clamp()
static float clamp (float value, float min, float max) static
Definition at line 18 of file pid.c.
Referenced by pid_compute(), and pid_init_advanced().
pid_compute()
float pid_compute (pid_t * pid, float setpoint, float measurement)
Calculate PID control output.
See detailed documentation in pid.h
Implementation algorithm:
Calculate error = setpoint - measurement
Proportional term: P = Kp × error Immediate response to current error
Integral term with anti-windup: integrator += error × dt integrator = clamp(integrator, integrator_min, integrator_max) <– Anti-windup I = Ki × integrator Eliminates steady-state error over time
Derivative term (on measurement, not error): derivative_raw = -(measurement - prev_measurement) / dt Note: Negative sign because we want to oppose changes in measurement If filtering enabled: derivative_filtered = α × derivative_filtered + (1-α) × derivative_raw derivative_raw = derivative_filtered D = Kd × derivative_raw Dampens oscillations and improves stability
Combine and clamp: output = P + I + D output = clamp(output, out_min, out_max)
Update state for next iteration: prev_error = error prev_measurement = measurement
Performance: ~20-40 CPU cycles on ARM Cortex-M4
Definition at line 164 of file pid.c.
References clamp(), pid_t::derivative_filtered, pid_t::derivative_lpf, pid_t::dt, pid_t::integrator, pid_t::integrator_max, pid_t::integrator_min, pid_t::kd, pid_t::ki, pid_t::kp, pid_t::out_max, pid_t::out_min, pid_t::prev_error, and pid_t::prev_measurement.
Referenced by main().
pid_init()
void pid_init (pid_t * pid, float kp, float ki, float kd, float dt, float out_min, float out_max)
Initialize PID controller with standard configuration.
See detailed documentation in pid.h
Implementation notes:
All state variables initialized to zero
Integrator limits calculated automatically: integrator_min/max = out_min/max / Ki
Division-by-zero protection: if Ki=0, integrator limits set to output limits
No derivative filtering enabled (derivative_lpf = 0)
Takes ~10-20 CPU cycles on typical embedded processors
Definition at line 41 of file pid.c.
References pid_t::derivative_filtered, pid_t::derivative_lpf, pid_t::dt, pid_t::integrator, pid_t::integrator_max, pid_t::integrator_min, pid_t::kd, pid_t::ki, pid_t::kp, pid_t::out_max, pid_t::out_min, pid_t::prev_error, and pid_t::prev_measurement.
Referenced by main().
pid_init_advanced()
void pid_init_advanced (pid_t * pid, float kp, float ki, float kd, float dt, float out_min, float out_max, float integrator_min, float integrator_max, float derivative_lpf)
Initialize PID controller with advanced options.
Provides custom integrator limits and derivative filtering.
Parameters
pid Pointer to PID structure
kp Proportional gain
ki Integral gain
kd Derivative gain
dt Sample time in seconds
out_min Minimum output limit
out_max Maximum output limit
integrator_min Min integrator limit (typically out_min/ki)
integrator_max Max integrator limit (typically out_max/ki)
derivative_lpf Derivative filter (0.0=none, 0.7-0.9=recommended)
Definition at line 84 of file pid.c.
References clamp(), pid_t::derivative_filtered, pid_t::derivative_lpf, pid_t::dt, pid_t::integrator, pid_t::integrator_max, pid_t::integrator_min, pid_t::kd, pid_t::ki, pid_t::kp, pid_t::out_max, pid_t::out_min, pid_t::prev_error, and pid_t::prev_measurement.
pid_reset()
void pid_reset (pid_t * pid)
Reset PID controller internal state.
See detailed documentation in pid.h
Implementation notes:
Zeros all state variables (integrator, history, filtered values)
Does NOT modify configuration (gains, limits, sample time)
Equivalent to re-initializing with same parameters
Takes ~5-10 CPU cycles
Safe to call at any time, even during active control
Use cases:
Starting control after inactivity (motor was stopped)
Large setpoint changes (avoid transient from old integrator state)
Fault recovery (clear potentially invalid state)
Mode switching (position control → velocity control)
Definition at line 220 of file pid.c.
References pid_t::derivative_filtered, pid_t::integrator, pid_t::prev_error, and pid_t::prev_measurement.