Embedded Motor PID Controller: firmware/src/main.c File Reference
main.c File Reference
PID motor controller demo application.
#include "motor.h"
#include "pid.h"
#include <stdio.h>
Macros
#define NUM_ITERATIONS 500 /* Simulation steps */
#define SAMPLE_TIME_MS 10 /* Control loop period (10ms = 100Hz) */
#define SAMPLE_TIME_S (SAMPLE_TIME_MS / 1000.0f)
#define PID_KP 0.8f /* Proportional gain */
#define PID_KI 0.3f /* Integral gain */
#define PID_KD 0.05f /* Derivative gain */
#define OUT_MIN -1.0f /* Full reverse */
#define OUT_MAX 1.0f /* Full forward */
#define SETPOINT 3.0f /* Desired motor speed */
Functions
int main (void)
Detailed Description
PID motor controller demo application.
Author
Onesmo Ogore
Version
1.0.0
Date
November 2025 @license MIT
Demonstrates PID-based motor speed control. Runs as desktop simulation with CSV output for analysis. For embedded use, replace with timer interrupt and hardware-specific motor functions.
Definition in file main.c.
Macro Definition Documentation
NUM_ITERATIONS
#define NUM_ITERATIONS 500 /* Simulation steps */
Definition at line 19 of file main.c.
Referenced by main().
OUT_MAX
#define OUT_MAX 1.0f /* Full forward */
Definition at line 30 of file main.c.
Referenced by main().
OUT_MIN
#define OUT_MIN -1.0f /* Full reverse */
Definition at line 29 of file main.c.
Referenced by main().
PID_KD
#define PID_KD 0.05f /* Derivative gain */
Definition at line 26 of file main.c.
Referenced by main().
PID_KI
#define PID_KI 0.3f /* Integral gain */
Definition at line 25 of file main.c.
Referenced by main().
PID_KP
#define PID_KP 0.8f /* Proportional gain */
Definition at line 24 of file main.c.
Referenced by main().
SAMPLE_TIME_MS
#define SAMPLE_TIME_MS 10 /* Control loop period (10ms = 100Hz) */
Definition at line 20 of file main.c.
SAMPLE_TIME_S
#define SAMPLE_TIME_S (SAMPLE_TIME_MS / 1000.0f)
Definition at line 21 of file main.c.
Referenced by main().
SETPOINT
#define SETPOINT 3.0f /* Desired motor speed */
Definition at line 33 of file main.c.
Referenced by main().
Function Documentation
main()
int main (void)
Definition at line 35 of file main.c.
References motor_get_speed(), motor_init(), motor_set_output(), motor_update(), NUM_ITERATIONS, OUT_MAX, OUT_MIN, pid_compute(), pid_init(), PID_KD, PID_KI, PID_KP, SAMPLE_TIME_S, and SETPOINT.