Embedded Motor PID Controller: firmware/include/pid.h File Reference
pid.h File Reference
Production-ready PID controller for embedded systems.
#include <stdint.h>
Classes
struct pid_t
PID Controller instance structure.
Functions
void pid_init (pid_t *pid, float kp, float ki, float kd, float dt, float out_min, float out_max)
Initialize PID controller with standard configuration.
void pid_init_advanced (pid_t *pid, float kp, float ki, float kd, float dt, float out_min, float out_max, float integrator_min, float integrator_max, float derivative_lpf)
Initialize PID controller with advanced options.
float pid_compute (pid_t *pid, float setpoint, float measurement)
Calculate PID control output.
void pid_reset (pid_t *pid)
Reset PID controller internal state.
Detailed Description
Production-ready PID controller for embedded systems.
Author
Onesmo Ogore
Version
1.0.0
Date
November 2025 @license MIT
Features: Anti-windup protection, derivative-on-measurement, derivative filtering, reentrant design, platform-agnostic C99.
Definition in file pid.h.
Function Documentation
pid_compute()
float pid_compute (pid_t * pid, float setpoint, float measurement)
Calculate PID control output.
Must be called periodically at the rate specified by dt. Uses derivative-on-measurement to avoid derivative kick.
Parameters
pid Pointer to initialized PID structure
setpoint Target value
measurement Current measured value
Returns
Control output clamped to [out_min, out_max]
Definition at line 110 of file pid.c.
References clamp(), pid_t::derivative_filtered, pid_t::derivative_lpf, pid_t::dt, pid_t::integrator, pid_t::integrator_max, pid_t::integrator_min, pid_t::kd, pid_t::ki, pid_t::kp, pid_t::out_max, pid_t::out_min, pid_t::prev_error, and pid_t::prev_measurement.
Referenced by main().
pid_init()
void pid_init (pid_t * pid, float kp, float ki, float kd, float dt, float out_min, float out_max)
Initialize PID controller with standard configuration.
Integrator limits are automatically calculated. No derivative filtering.
Parameters
pid Pointer to PID structure
kp Proportional gain
ki Integral gain (0 to disable)
kd Derivative gain (0 to disable)
dt Sample time in seconds (must match loop period)
out_min Minimum output limit
out_max Maximum output limit
Definition at line 25 of file pid.c.
References pid_t::derivative_filtered, pid_t::derivative_lpf, pid_t::dt, pid_t::integrator, pid_t::integrator_max, pid_t::integrator_min, pid_t::kd, pid_t::ki, pid_t::kp, pid_t::out_max, pid_t::out_min, pid_t::prev_error, and pid_t::prev_measurement.
Referenced by main().
pid_init_advanced()
void pid_init_advanced (pid_t * pid, float kp, float ki, float kd, float dt, float out_min, float out_max, float integrator_min, float integrator_max, float derivative_lpf)
Initialize PID controller with advanced options.
Provides custom integrator limits and derivative filtering.
Parameters
pid Pointer to PID structure
kp Proportional gain
ki Integral gain
kd Derivative gain
dt Sample time in seconds
out_min Minimum output limit
out_max Maximum output limit
integrator_min Min integrator limit (typically out_min/ki)
integrator_max Max integrator limit (typically out_max/ki)
derivative_lpf Derivative filter (0.0=none, 0.7-0.9=recommended)
Definition at line 68 of file pid.c.
References clamp(), pid_t::derivative_filtered, pid_t::derivative_lpf, pid_t::dt, pid_t::integrator, pid_t::integrator_max, pid_t::integrator_min, pid_t::kd, pid_t::ki, pid_t::kp, pid_t::out_max, pid_t::out_min, pid_t::prev_error, and pid_t::prev_measurement.
pid_reset()
void pid_reset (pid_t * pid)
Reset PID controller internal state.
Clears integrator, previous values, and filtered derivative. Preserves configuration (gains, limits, sample time).
Parameters
pid Pointer to PID structure
Definition at line 147 of file pid.c.
References pid_t::derivative_filtered, pid_t::integrator, pid_t::prev_error, and pid_t::prev_measurement.